spring.application.name=JP

spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db
spring.datasource.username=campus2023
spring.datasource.password=campus2023

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ERRORES
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# JWT
jwt.secret=esta-es-una-clave-secreta-muy-larga-para-logitrack-2026
jwt.expiration=86400000